import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import{createClient}from"@supabase/supabase-js";import"./styles.css";
const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||"https://ekyvogemusxmgeefrqmc.supabase.co",import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||"");
const menu=[["dashboard","Dashboard"],["patients","Patients"],["programmes","Programmes"],["schedule","Scheduler"],["records","Records & AI review"],["alerts","Vital alerts"],["nutrition","Nutrition"],["medicines","Medicine catalogue"],["prescriptions","Prescriptions"],["orders","Store & orders"]];
function App(){const[s,setS]=useState(null),[page,setPage]=useState("dashboard"),[loading,setLoading]=useState(true);useEffect(()=>{supabase.auth.getSession().then(({data})=>{setS(data.session);setLoading(false)});const{x}=supabase.auth.onAuthStateChange((_e,ss)=>setS(ss));return()=>x.subscription.unsubscribe()},[]);if(loading)return <div className="loading">LIVYA</div>;return s?<Shell page={page} setPage={setPage} session={s}/>:<Login/>}
function Login(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState("");async function go(e){e.preventDefault();const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}return <div className="login"><form onSubmit={go}><b>LIVYA</b><h1>Admin portal</h1><p>Secure access for the LIVYA care team.</p><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{msg&&<small>{msg}</small>}<button>Sign in</button></form></div>}
function Shell({page,setPage,session}){return <div className="layout"><aside><div className="logo">LIVYA</div><div className="sub">SMART HEALTH PLATFORM</div>{menu.map(([id,l])=><button className={page===id?"sel":""} onClick={()=>setPage(id)} key={id}>{l}</button>)}<div className="asidefoot"><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><section className="main"><header><div><span>Home / {title(page)}</span><h1>{title(page)}</h1></div><div className="headright"><button className="add">+ Add patient</button><div className="doctor">Dr. Krishnan · ●</div></div></header><Content page={page}/></section></div>}
const title=p=>({dashboard:"Good morning, Dr. Krishnan",patients:"Patients",programmes:"Programmes",schedule:"Scheduler",records:"Records & AI review",alerts:"Vital alerts",nutrition:"Nutrition",medicines:"Medicine catalogue",prescriptions:"Prescriptions",orders:"Store & orders"}[p]||"LIVYA");
function Content({page}){if(page==="dashboard")return <Dashboard/>;const labels={patients:["Patients","Active members","Name","Programme","Status","Last activity"],programmes:["Programmes","Programmes & plans","Programme","Members","Duration","Status"],schedule:["Scheduler","Upcoming bookings","Date","Patient","Service","Clinician"],records:["Records & AI review","Recent records","Patient","Record","AI review","Status"],alerts:["Vital alerts","Recent alerts","Patient","Metric","Reading","Action"],nutrition:["Nutrition","Nutrition plans","Patient","Plan","Progress","Review"],medicines:["Medicine catalogue","Medicine catalogue","Medicine","Category","Stock","Status"],prescriptions:["Prescriptions","Prescriptions","Patient","Medicine","Dose","Status"],orders:["Store & orders","Store & orders","Order","Patient","Amount","Status"]};let a=labels[page]||labels.patients;return <TablePage heading={a[0]} sub={a[1]} cols={a.slice(2)}/> }
function Dashboard(){return <><div className="stats">{[["1,284","Members","↑ 12.4%"],["7","Bookings today","3 pending"],["12","Vital alerts","4 urgent"],["94","Orders","8 pending"]].map(x=><div className="stat"><span>{x[1]}</span><b>{x[0]}</b><small>{x[2]}</small></div>)}</div><div className="two"><TablePage heading="Recent patients" sub="Latest member activity" cols={["Patient","Programme","Status","Last activity"]}/><div className="card"><h2>Care team tasks</h2>{["Review 4 urgent vital alerts","Approve 3 programme changes","2 lab reports awaiting review","Send today's follow-up reminders"].map((x,i)=><div className="task"><i className={i<2?"hot":""}></i><span>{x}</span><b>{i+1}</b></div>)}</div></div></>}
function TablePage({heading,sub,cols}){const rows=["Priya Raghavan","Arjun Menon","Meera Krishnan","Rahul Shah","Ananya Iyer","Karthik Rao"];return <div className="card tablecard"><div className="cardhead"><div><h2>{heading}</h2><p>{sub}</p></div><button className="outline">Export</button></div><div className="table"><div className="tr th">{cols.map(c=><span>{c}</span>)}</div>{rows.map((r,i)=><div className="tr"><span><b>{r}</b></span><span>{["Metabolic Reset","Nutrition","Metabolic Reset","Weight care"][i%4]}</span><span><em className={i===2?"warn":""}>{i===2?"Review":"Active"}</em></span><span>{i+1}h ago</span></div>)}</div></div>}
createRoot(document.getElementById("root")).render(<App/>);